name: Python CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --deploy --ignore-pipfile

    - name: Code quality checks
      run: |
        pipenv run black . --check
        pipenv run isort --check-only .
        pipenv run flake8 .

